#!/usr/bin/env node
// Structural QA check for a .md file generated by the linkedin-resume-optimizer skill.
// Not a full test suite (the skill is prompt-based, not code) — this is a repeatable
// regression guard against the same class of bugs that have been found by hand:
// missing sections, bullet counts outside 3-5, banned phrases, wrong Open to Work
// defaults. Run after generating any output file, or when editing SKILL.md, against
// a known-good fixture.
//
// Usage: node scripts/lint-output.mjs <path-to-generated.md>
// Exit code: 0 = no issues, 1 = issues found (printed to stderr).

import { readFileSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const skillRoot = path.resolve(__dirname, "..");

const target = process.argv[2];
if (!target) {
  console.error("Usage: node scripts/lint-output.mjs <path-to-generated.md>");
  process.exit(1);
}

const filePath = path.resolve(target);
if (!existsSync(filePath)) {
  console.error(`File not found: ${filePath}`);
  process.exit(1);
}

const text = readFileSync(filePath, "utf8");
const lines = text.split(/\r?\n/);
const isLinkedIn = /-linkedin-otimizado\.md$/.test(filePath);
const isCurriculo = /-curriculo-otimizado\.md$/.test(filePath);

const issues = [];
const warnings = [];

// --- 1. Required sections present ---
const requiredSections = isLinkedIn
  ? ["## Headline", "## About", "## Top skills", "## Experiências", "## Educação", "## Score", "## Resumo", "## Open to Work", "## SSI", "## Pendências"]
  : isCurriculo
  ? ["## Cabeçalho", "## Resumo Profissional", "## Experiência Profissional", "## Educação", "## Score", "## Resumo", "## Pendências"]
  : [];

if (!isLinkedIn && !isCurriculo) {
  warnings.push(
    "Filename doesn't match *-linkedin-otimizado.md or *-curriculo-otimizado.md — skipping section/shape checks, only running phrase/visibility checks."
  );
}

for (const section of requiredSections) {
  if (!text.includes(section)) {
    issues.push(`Missing required section: "${section}"`);
  }
}

// --- 2. Bullet count per experience: 3-5 in the "Depois" block ---
// Find each "### " subsection, then within it find the bullets that appear
// after the last "Depois" marker before the next heading.
const headingIdx = [];
lines.forEach((line, i) => {
  if (/^#{2,3} /.test(line)) headingIdx.push(i);
});
headingIdx.push(lines.length);

for (let h = 0; h < headingIdx.length - 1; h++) {
  const start = headingIdx[h];
  const end = headingIdx[h + 1];
  const headingLine = lines[start];
  if (!/^### /.test(headingLine)) continue;
  // Only check subsections that look like a role (has a date range with an en-dash or hyphen)
  const block = lines.slice(start, end);
  const depoisIdx = block.map((l) => l.trim()).lastIndexOf("Depois:") !== -1
    ? block.map((l) => l.trim()).lastIndexOf("Depois:")
    : block.findIndex((l) => /^Depois/.test(l.trim()));
  if (depoisIdx === -1) continue; // no Antes/Depois pair here (e.g. Educação subsection)
  const after = block.slice(depoisIdx + 1);
  const bulletCount = after.filter((l) => /^\s*(>\s*)?-\s+/.test(l)).length;
  if (bulletCount === 0) continue; // likely a pendência block with no bullets yet, not our concern here
  if (bulletCount < 3 || bulletCount > 5) {
    warnings.push(
      `"${headingLine.replace(/^#+\s*/, "")}": ${bulletCount} bullet(s) in "Depois" — expected 3-5.`
    );
  }
}

// --- 3. Banned phrases (best-effort — flags all matches, including inside "Antes:" quotes,
//         since those are legitimate critique targets; read the surrounding line to judge). ---
const bannedPath = path.join(skillRoot, "references", "banned-phrases.md");
if (existsSync(bannedPath)) {
  const bannedText = readFileSync(bannedPath, "utf8");
  const terms = [...bannedText.matchAll(/^- (.+)$/gm)]
    .map((m) => m[1].split(" (")[0].trim())
    .filter((t) => t && !t.includes("|"));
  lines.forEach((line, i) => {
    for (const term of terms) {
      const re = new RegExp(`\\b${term.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\b`, "i");
      if (re.test(line)) {
        warnings.push(`Line ${i + 1}: possible banned phrase "${term}" — verify it's not in a final "Depois" block.`);
      }
    }
  });
}

// --- 4. Open to Work regression guard (LinkedIn only) ---
if (isLinkedIn && text.includes("## Open to Work")) {
  if (/All LinkedIn members/i.test(text)) {
    issues.push('Open to Work visibility mentions "All LinkedIn members" — skill rule requires "Recruiters only" always.');
  }
  if (!/Recruiters only/i.test(text)) {
    warnings.push('Open to Work section doesn\'t mention "Recruiters only" — expected visibility recommendation is missing.');
  }
  if (/\bFlexible\b/.test(text) && /Start date/i.test(text)) {
    warnings.push('Start date section mentions "Flexible" — skill rule requires always recommending "Immediately, I am actively applying".');
  }
}

// --- 5. [FALTA DADO] hygiene: flagged inline should also be listed in Pendências ---
const inlineFlags = [...text.matchAll(/\[FALTA DADO:[^\]]*\]/g)].length;
const pendenciasIdx = lines.findIndex((l) => l.trim() === "## Pendências");
if (inlineFlags > 0 && pendenciasIdx === -1) {
  issues.push(`${inlineFlags} inline [FALTA DADO] marker(s) found but no "## Pendências" section exists.`);
}

// --- Report ---
if (issues.length === 0 && warnings.length === 0) {
  console.log(`OK — no issues found in ${path.basename(filePath)}.`);
  process.exit(0);
}

if (warnings.length) {
  console.log(`Warnings (${warnings.length}):`);
  warnings.forEach((w) => console.log(`  - ${w}`));
}
if (issues.length) {
  console.error(`\nIssues (${issues.length}):`);
  issues.forEach((e) => console.error(`  - ${e}`));
  process.exit(1);
}
process.exit(0);
