"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
${custom.git_branch_outside_home}\
$git_status\
$cmd_duration\
$line_break\
$character"""

[username]
style_user = "#c678dd"
style_root = "bold #ff6c6b"
format = "[$user]($style) | "
show_always = true

[hostname]
style = "#5b6268"
disabled = true
format = "[$hostname]($style) "
ssh_only = false
aliases = { "MacBook-Air" = "air" }

[directory]
style = "#51afef"
format = "[$path]($style) "
truncation_length = 3

[git_branch]
disabled = true

[custom.git_branch_outside_home]
command = "git branch --show-current"
when = 'test "$PWD" != "$HOME" && git rev-parse --is-inside-work-tree >/dev/null 2>&1'
format = " :: [git:$output]($style)"
style = "#5b6268"
shell = ["zsh", "--no-rcs"]

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "#5b6268"

[git_status]
format = " $all_status$ahead_behind"
style = "#98be65"
conflicted = "!"
untracked = "?"
modified = "*"
staged = "+"
renamed = ">"
deleted = "x"
stashed = "$"
ahead = "^"
behind = "v"
diverged = "<>"
up_to_date = ""

[cmd_duration]
format = " took:$duration "
style = "#ecbe7b"

[haskell]
symbol = "λ"
style = "#c678dd"
format = '([$symbol $version]($style) )'

[python]
format = "[$virtualenv]($style) "
style = "#5b6268"
detect_extensions = []
detect_files = []

[character]
success_symbol = "[λ](bold #98be65)"
error_symbol = "[λ](bold #ff6c6b)"
vimcmd_symbol = "[λ](bold #4db5bd)"
