"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
${custom.git_branch_outside_home}\
$git_status\
$cmd_duration\
$line_break\
$character"""

[username]
style_user = "#d3869b"
style_root = "bold #fb4934"
format = "[$user]($style) | "
show_always = true

[hostname]
style = "#928374"
disabled = true
format = "[$hostname]($style) "
ssh_only = false
aliases = { "MacBook-Air" = "air" }

[directory]
style = "#83a598"
format = "[$path]($style) "
truncation_length = 3

[git_branch]
disabled = true

[custom.git_branch_outside_home]
command = "git branch --show-current"
when = 'test "$PWD" != "$HOME" && git rev-parse --is-inside-work-tree >/dev/null 2>&1'
format = " :: [git:$output]($style)"
style = "#928374"
shell = ["zsh", "--no-rcs"]

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "#928374"

[git_status]
format = " $all_status$ahead_behind"
style = "#8ec07c"
conflicted = "!"
untracked = "?"
modified = "*"
staged = "+"
renamed = ">"
deleted = "x"
stashed = "$"
ahead = "^"
behind = "v"
diverged = "<>"
up_to_date = ""

[cmd_duration]
format = " took:$duration "
style = "#fabd2f"

[haskell]
symbol = "λ"
style = "#d3869b"
format = '([$symbol $version]($style) )'

[python]
format = "[$virtualenv]($style) "
style = "#928374"
detect_extensions = []
detect_files = []

[character]
success_symbol = "[λ](#b8bb26)"
error_symbol = "[λ](#fb4934)"
vimcmd_symbol = "[λ](#8ec07c)"
