"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
${custom.git_branch_outside_home}\
$git_status\
$cmd_duration\
$line_break\
$character"""

[username]
style_user = "#c6c6c6"
style_root = "bold #e32791"
format = "[$user]($style) | "
show_always = true

[hostname]
style = "#767676"
disabled = true
format = "[$hostname]($style) "
ssh_only = false
aliases = { "MacBook-Air" = "air" }

[directory]
style = "#008ec4"
format = "[$path]($style) "
truncation_length = 3

[git_branch]
disabled = true

[custom.git_branch_outside_home]
command = "git branch --show-current"
when = 'test "$PWD" != "$HOME" && git rev-parse --is-inside-work-tree >/dev/null 2>&1'
format = " :: [git:$output]($style)"
style = "#767676"
shell = ["zsh", "--no-rcs"]

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "#767676"

[git_status]
format = " $all_status$ahead_behind"
style = "#5fd7a7"
conflicted = "!"
untracked = "?"
modified = "*"
staged = "+"
renamed = ">"
deleted = "x"
stashed = "$"
ahead = "^"
behind = "v"
diverged = "<>"
up_to_date = ""

[cmd_duration]
format = " took:$duration "
style = "#ffff87"

[haskell]
symbol = "λ"
style = "#a790d5"
format = '([$symbol $version]($style) )'

[python]
format = "[$virtualenv]($style) "
style = "#767676"
detect_extensions = []
detect_files = []

[character]
success_symbol = "[λ](bold #d75f87)"
error_symbol = "[λ](bold #e32791)"
vimcmd_symbol = "[λ](bold #d75f87)"
vimcmd_visual_symbol = "[❮](bold #d75f87)"
vimcmd_replace_symbol = "[❮](bold #e32791)"
vimcmd_replace_one_symbol = "[❮](bold #e32791)"
